- client.go
some webdav doesn't have displayname. for example box.com
> look href if displayname not exists

- client.go
Hi,
I am trying to access WebDAV servers that authenticate users based on client certificates. For this, I need to set up an http.Transport with its TLSClientConfig field properly initialised.
This call would allow to override the default transport, which should also allow to override proxy settings, timeouts and the like.
Regards.
> Add SetTransport method

- client.go
In `Read`/`ReadStream` no HTTP response code handling is done. The expected behaviour IMO is to  promote 404 and similar errors to actual `err` responses.
> Handle error response when reading a file.

- digestAuth.go
The problem was that `Apache HTTPS Server` does not provide `opaque` field in `401 Unauthorized` response, but `gowebdav` trying to read it, and to add this field to `Authorization` header of the next request.
This is example of `gowebdav <--> Apache HTTPS Server` interaction to visualize problem and show the solution:
**Client request**
```
PROPFIND /user HTTP/1.0
Host: mydav.me
```
**Server response**
```
Connection →       Keep-Alive
Content-Length →   457
Content-Type →     text/html; charset=iso-8859-1
Date →             Wed, 20 Jun 2018 00:08:07 GMT
Keep-Alive →       timeout=5, max=100
Server →           Apache/2.4.18 (Ubuntu)
WWW-Authenticate → Digest realm="webdav", 
nonce="luTmlwdvBQA=7a7e41a1027643ba1f7b3c34d4e52133e2ee6a3c", 
algorithm=MD5, 
qop=auth
<!DOCTYPE HTML> …
```
> Bug #14 fixed

- .travis.yml
- client.go
- requests.go
When I reading sources of `gowebdav` I found that `Client.createParentCollection()` method is required in some places, and marked with `TODO` statements.
So, in this pull request I do:
1. Add `Client.createParentCollection(itemPath string) error` method to `Client`'s structure
2. Use this method inside `Client.Write(path string, data []byte, _  os.FileMode) error` method in case of `409` response
3. Use this method inside `Client.WriteStream(path string, stream io.Reader, _  os.FileMode) error` method
4. Use this method inside `Client.copymove(method string, oldpath string, newpath string, overwrite bool) error` method in case of `409` response
_NOTE_: I think `Client.Write()` and `Client.WriteStream()` methods should be refactored to use `c.createParentCollection()` in the same way, …
> Creating parent collection method was added

- requests.go
When error happend, rs should be nil, defer cause panic.  Should check error first.
Happended here.
> Fix early defer panic.

- requests.go
Hi,
I discovered the problem that createParentCollection might be called with no or root directory, resulting in errors with MkdirAll. The attached commit simply adds a check for this.
Best Regards
> Added check of parentPath in createParentCollection

- file.go
Very useful when iterating over ReadDir results and wanting to do some operation on them.
> Add File.Path to return the full path

- client.go
- requests.go
Closes #35 
This adds the ability to define custom interceptors, like so:
```go
// Disable chunked encoding for better compatibility
webDAVClient.SetInterceptor(func(method string, rq *http.Request) {
if method == "PUT" && rq.Body != nil {
b, err := ioutil.ReadAll(rq.Body)
if err != nil {
panic(err)
}
rq.ContentLength = int64(len(b))
rq.Body = ioutil.NopCloser(bytes.NewReader(b))
}
})
```
See https://github.com/pojntfx/growlapse/blob/main/main.go#L145-L157 for a usage example. This allows to for example upload to servers which don't have chunked encoding support, such as the public Nextcloud instances hosted by [Hetzner](https://www.hetzner.com/storage/storage-share).
> Add ability to define custom interceptors (fixes #35)

- requests.go
I've been connecting to my Synology's WebDAV and have been encountering semi-regular panics with the following stacktrace:
```plaintext
github.com/studio-b12/gowebdav.(*Client).copymove(0xc0004ec140, 0x12c5bd5, 0x4, 0xc01a132dc0, 0x4e, 0xc0190efe80, 0x3a, 0x1, 0x0, 0x0)
/home/runner/go/pkg/mod/github.com/studio-b12/gowebdav@v0.0.0-20210203212356-8244b5a5f51a/requests.go:141 +0xbc
github.com/studio-b12/gowebdav.(*Client).Rename(...)
/home/runner/go/pkg/mod/github.com/studio-b12/gowebdav@v0.0.0-20210203212356-8244b5a5f51a/client.go:302
…
```
It appears that this is simply due to not properly handling request errors during copy/move.
> Handle request errors in copymove

- utils.go
- utils_test.go
Fix index out of range runtime error when empty string is provided to FixSlashes. When someone provides an empty string to e.g. ReadDir, this will cause a runtime error in FixSlashes.
> Fix index out of range runtime error when empty string is provided to FixSlashes

- client.go
- utils.go
It passes "Range: bytes=X-Y" and if the server returns HTTP 206,
we know it complied with the request.
For servers that don't understand range and return HTTP 200 instead we
discard some bytes and limit the result to emulate this behavior.
This will greatly help https://github.com/kopia/kopia which relies on
partial reads from pack blobs.
Fixes #23
> added ReadStreamRange() method to efficiently read a range of data

- .github/workflows/tests.yml
This pull request adds a GitHub Actions workflow configuration to perform go unit tests on push and pull requests. This might become handy due to the integration between GitHub repositories and GitHub Actions to validate pull requests and code pushes alongside the TravisCI pipeline.
All unit tests are performed on the latest supported go versions (`1.16` and `1.17` in this case).
> Add GitHub Actions Workflow for Unit Tests

- .github/workflows/artifacts.yml
This pull request adds a GitHub Actions workflow configuration to create binaries for the CLI application and uploads them as artifacts to the workflow so that users can easily access latest builds of the CLI tool without cloning and compiling themselves.
The binaries are cross-compiled for Linux, Windows and Darwin based systems on x86-64 and ARM64 architectures.
> Add Artifacts Workflow

- requests.go
I tried to upload a large file (~30GB) over night with on my Raspberry Pi using the CLI client. Therefore I opened up a Docker container with the binary and the file to upload inside and started the upload from there. I noticed that the upload always gets canceled after a few minutes with log output `Killed`. 
The problem occurs because the contents of the file are written into a buffer on upload, which filled up the RAM of the Pi (4GB) which eventually caused Linux to kill the process.
https://github.com/studio-b12/gowebdav/blob/73a7f0bf3780929a467543d2c09b2886c26170e2/requests.go#L12-L16
I was also able to reproduce this on my Windows system.
I changed the `req` function so that it checks if the passed `body` Reader implements `io.Seeker`. If this is the case, the streams cursor will be …
> Use seeker when available on request body

- .gitignore
- requests.go
Well, I noticed that a nil pointer panic is caused under some circumstances when `Client#req` is called with `body` as `nil`.  
This PR should fix that problem.
Also, in order of the changes I've removed the nil check from the request inside the non-auth retry condition, because `retryBuf` is always `nil` when `body` was `nil` initially.
Additionally, I've added the `.vscode/` directory to the gitignore, just for convenience when working with VSC.
> Fix crash when no body is passed to `Client#req`

- client.go
- cmd/gowebdav/main.go
- errors.go
- requests.go
- utils.go
I found some time to try to tackle the error handling issue described in #28.
Therefore, all request methods which only returned status code do now return proper error values as well. Also, path errors now contain an instance of `StatusError` which contains the erroneous status code. This makes handling specific errors more trivial.
As well, I put all error related functions and structures into `errors.go` to give a better overview over the codebase.
While testing, I also noticed that `Client#req` fails when a file stream is passed as body and the request is repeatet due to an authentication error. I found out that - for whatever reason - `http.Client#Do` closes the passed `io.Closer` stream.
Here is a quick demonstration of this behavior: https://go.dev/play/p/OouD3-GAD0M
This causes …
> Improve Error Handling

- client.go
Refer to  [http protocol RFC documentation](https://www.rfc-editor.org/rfc/rfc9110.html#name-byte-ranges:~:text=14.1.2.-,Byte%20Ranges,-The%20%22bytes%22%20range)
> support get range offset=2 length=-1

- requests.go
Client.Stat was not returning a proper Go err for not found files, the
ideal way to check this is using `errors.Is(err, fs.ErrNotExist)` but
the client was returning a generic error.
I've updated the `propfind` to take 404 errors into account, retuning
the above error making easier to evaluate that kind of situations.
> feat: handle 404 on propfind

- client.go
expose a `SetJar` method to set a `http.CookieJar` to the http client
> Fixes #64 Support for cookies

- .github/workflows/tests.yml
- README.md
- auth.go
- auth_test.go
- basicAuth.go
- basicAuth_test.go
- client.go
- client_test.go
- cmd/gowebdav/main.go
- digestAuth.go
- digestAuth_test.go
- errors.go
- requests.go
The main goal was to simplify the `req` method in
`request.go` and making it easier to add more authentication methods.
All the magic went into the `auth.go` file.
This feature introduces an `Authorizer` which acts as an
`Authenticator` factory. Under the hood it creates an authenticator
shim per request, which delegates the authentication flow
to our authenticators.
The authentication flow itself is broken down into `Authorize' and
`Verify' steps to encapsulate and control complex authentication challenges.
Furthermore, the default `NewAutoAuth` authenticator can be overridden
by a custom implementation for more control over flow and resources.
The `NewBacisAuth` Authorizer gives us the feel of the old days.
> Improves the authentication flow

- digestAuth.go
- digestAuth_test.go
Hi studio-b12 members !
First of all, I'd like to thank you for this wonderful/easy-to-use Webdav Go package 😃 
I'm opening this PR because I recently faced an issue trying to connect to a Webdav server using Digest auth mechanism.
Client successfully connected to this server using digest authenticator, but after some time it was rejected by the server with 401 status codes.
I took a look at the [RFC2617](https://www.ietf.org/rfc/rfc2617.txt) (Section `3.2.1 The WWW-Authenticate Response Header`), and it seems that the server can invalidate the generated `nonce` value after some time (which is my case). However, in such case, the `stale` directive is added to the `WWW-Authenticate` header, indicating to the client to re-authenticate without reprompting the user for username and password. …
> Add support for stale directive for digest authenticator

- client.go
- client_test.go
- requests.go
Since there is some webdav server implementation (such as nextcloud) give unexpected behavior when there is no content length is set in the put request. Therefore, I introduce the contentLength parameter to the `*Client.put()` method to provide the correct content length of the body to the server to prevent the behavior mention above.
> Provide content length for the put method
